### ISSUE TITLE
Latest Uploads collage is empty

### ISSUE THREAD

**Issue by rlaphoenix** [EwolBash/opsdark#1]
Stylesheet: /static/styles/ops_dark/redwithopslogo.css

![image](https://user-images.githubusercontent.com/17136956/149645036-d1266607-cdcc-4ea8-9e5b-a58fa53056e5.png)

**Comment by EwolBash** [comment]
Should be fixed thanks to a user on the forums. @rlaphoenix 

Let me know if it still exists. Might have to clear cache for it to show if F5 doesn't work.

**Comment by rlaphoenix** [comment]
Can confirm it works. Thanks.
